# CI de Nível 01 - Disparo manual a partir de 1 clique

name: 'Execução N1'

on:
  workflow_dispatch: 


jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      # Baixa o código do repo
      - uses: actions/checkout@v4

      # Instala o Node.js
      - uses: actions/setup-node@v4 
        with:
          node-version: 20   

      # Instala dependências declaradas no package.json
      - name: Instalar dependências
        run: npm ci      

      # Executa os testes
      - name: Executando os testes
        run: npm test

